# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json

blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion
    url: https://github.com/anthropics/claude-code/issues
    about: Ask questions, share ideas, or discuss Claude Code and MCP projects
  - name: 📖 MCP Documentation
    url: https://modelcontextprotocol.io
    about: Read about the Model Context Protocol specification and implementation guides
  - name: ⚡ Claude Code
    url: https://claude.ai/code
    about: Official Claude Code documentation and resources